version: 2
jobs:
  build_couchdb_2:
    docker:
      - image: crystallang/crystal:nightly
        environment:
          TEST_DB: "http://admin:1234@localhost:5984"
      - image: couchdb:2
        environment:
          COUCHDB_USER: "admin"
          COUCHDB_PASSWORD: 1234
    environment:
    steps:
      - checkout
      - run: crystal --version
      - run: shards install
      - run: crystal spec --junit_output=test_results
      - store_test_results:
          path: test_results
      - run: crystal docs
      - store_artifacts:
          path: docs
          destination: /docs
  build_couchdb_3:
    docker:
      - image: crystallang/crystal:nightly
        environment:
          TEST_DB: "http://admin:1234@localhost:5984"
      - image: couchdb:3
        environment:
          COUCHDB_USER: "admin"
          COUCHDB_PASSWORD: 1234
    environment:
    steps:
      - checkout
      - run: crystal --version
      - run: shards install
      - run: crystal spec --junit_output=test_results
      - store_test_results:
          path: test_results
      - run: crystal docs
      - store_artifacts:
          path: docs
          destination: /docs
workflows:
  version: 2
  commit:
    jobs:
      - build_couchdb_2
      - build_couchdb_3
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build_couchdb_2
      - build_couchdb_3
